### ISSUE TITLE
TT Embedding experiment

### ISSUE THREAD

**Issue by SunYanCN** [philip-bl/tensor_train_rnn#1]
Hello! I am very interested in the experiment of TT Embedding. However, the original author's code seems to have many problems. Can you release your code?

**Comment by philip-bl** [comment]
@SunYanCN I've asked the person responsible for that experiment to upload code here.

**Comment by SunYanCN** [comment]
Thank you very much! I hope I can do some further attempts.

**Comment by davankov** [comment]
@SunYanCN Hello! I just used code from https://github.com/KhrulkovV/tt-pytorch and run their experiment.

**Comment by SunYanCN** [comment]
@davankov I also tried running their code, but there have been a lot of problems.

**Comment by davankov** [comment]
@SunYanCN What kind of problems? I can upload jupyter notebook which run only one experiment, but works good. Are you interested?

**Comment by SunYanCN** [comment]
@davankov Yes,Thank You! 
https://github.com/KhrulkovV/tt-pytorch/issues/2
I saw the author replied to me, but he replied too slowly.

**Comment by SunYanCN** [comment]
@philip-bl @davankov 
Thanks again for your report, I think this is very helpful for my research.
